### ISSUE TITLE
HW6

### ISSUE THREAD

**Issue by shpakb** [shpakb/cshw#6]

**Comment by YakutovDmitriy** [comment]
* `cutarray`. You have two implementations. Please remove one of them
* `getmoments`. Fix it
* `checkequal`. You assume that dimension of `a` and `b` is 1. it is not true.
* `getones`. Please find out how to implement this function in one line
* Other functions are ok

**Comment by shpakb** [comment]
Fixed everithing exept getmoments. My np.array([2, 1, 9]).mean() still equal to 4.0

**Comment by YakutovDmitriy** [comment]
* `getmoments`. Yeah, I have very strange bug in task description. Please fix your implementation
* `cutarray`. Please use the following test:
    * `a = np.array([[1., 2.], [3., 4.]])`;
    * `minvalue = 3.5`;
    * `maxvalue = 7.0`
* Other functions are ok. Actually in functions `getones` I mean `np.eye`

**Comment by shpakb** [comment]
Fixed

**Comment by YakutovDmitriy** [comment]
* `cutarray` - ok
* `cutarray`. Your implementations is still incorrect. Read the statement
